# Generated by Django 3.0.14 on 2023-12-14 16:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle_grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('is_ship', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Battlefield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comments', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('battlefield_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_battlefield_1', to='mybattleship.Battlefield')),
                ('battlefield_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_battlefield_2', to='mybattleship.Battlefield')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('life', models.IntegerField()),
                ('is_dead', models.BooleanField()),
                ('battle_grids', models.ManyToManyField(to='mybattleship.Battle_grid')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybattleship.Game')),
            ],
        ),
        migrations.AddField(
            model_name='battlefield',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybattleship.Player'),
        ),
        migrations.AddField(
            model_name='battle_grid',
            name='battlefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybattleship.Battlefield'),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('battle_grid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mybattleship.Battle_grid')),
                ('game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybattleship.Game')),
            ],
            options={
                'unique_together': {('game', 'order')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='battle_grid',
            unique_together={('battlefield', 'x', 'y')},
        ),
    ]
