# Generated by Django 3.0.14 on 2023-12-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybattleship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='game',
        ),
    ]
