# Generated by Django 4.2.6 on 2023-11-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybattleship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comments',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybattleship.game'),
        ),
    ]
