# Generated by Django 3.0.14 on 2023-12-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybattleship', '0003_battle_grid_is_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='battlefield',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybattleship.Battlefield'),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('battlefield', 'order')},
        ),
        migrations.RemoveField(
            model_name='move',
            name='game',
        ),
    ]
