# Generated by Django 3.0.14 on 2023-12-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybattleship', '0004_auto_20231214_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefield',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
