# Generated by Django 3.0.14 on 2023-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybattleship', '0005_battlefield_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_move',
            field=models.BooleanField(default=True),
        ),
    ]
