# Generated by Django 4.2.9 on 2024-01-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybattleship', '0009_remove_battlefield_opponent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='move',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mybattleship.game'),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('game', 'order')},
        ),
        migrations.RemoveField(
            model_name='move',
            name='battlefield',
        ),
    ]
