# Generated by Django 4.2.9 on 2024-01-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybattleship', '0012_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
